(function () {
  const DATA = {
    nome: [
      "ana", "arthur", "alice",
      "bruno", "beatriz", "bernardo",
      "camila", "carlos", "clara",
      "daniel", "daniela", "diego",
      "eduardo", "elena", "eric",
      "felipe", "fernanda", "fernando",
      "gustavo", "gabriela", "guilherme",
      "heitor", "helena", "hugo",
      "igor", "isabela", "icaro",
      "joao", "julia", "jorge",
      "kevin", "karina", "kaio",
      "lucas", "larissa", "leonardo",
      "matheus", "mariana", "marcos",
      "nicolas", "natalia", "nathan",
      "otavio", "olivia", "orlando",
      "pedro", "patricia", "paulo",
      "querino", "quesia", "quiteria",
      "rafael", "rafaela", "rodrigo",
      "samuel", "sofia", "savio",
      "thiago", "tatiana", "tomas",
      "ulisses", "uriel", "ursula",
      "victor", "valentina", "vinicius",
      "william", "waleria", "wagner",
      "xavier", "xenia", "xisto",
      "yuri", "yasmin", "yago",
      "zacarias", "zelia", "zeca"
    ],
    animal: [
      "abelha", "aguia", "anta",
      "borboleta", "baleia", "bufalo",
      "cachorro", "gato", "cavalo",
      "dinossauro", "dromedario", "degual",
      "elefante", "egua", "esquilo",
      "flamingo", "foca", "formiga",
      "girafa", "galinha", "hipopotamo",
      "hiena", "hamster", "iguana",
      "impala", "iaque", "jacare",
      "javali", "jaguatirica", "koala",
      "kudu", "kakapo", "leao",
      "lobo", "lagarto", "macaco",
      "morcego", "mosca", "naja",
      "narval", "nhandu", "onca",
      "ovelha", "orangotango", "pato",
      "pinguim", "pantera", "quati",
      "quero-quero", "queixada", "rato",
      "raposa", "rinoceronte", "sapo",
      "serpente", "salamandra", "tigre",
      "tubarao", "tartaruga", "urubu",
      "urso", "unicornio", "vaca",
      "veado", "vagalume", "wallaby",
      "wombat", "weimaraner", "xareu",
      "xexeu", "xiu", "yorkie",
      "yorkshire", "yak", "zebra",
      "zangao", "zebu"
    ],
    objeto: [
      "anel", "agulha", "almofada",
      "bola", "boneca", "bacia",
      "cadeira", "caneta", "cama",
      "dado", "dedal", "disco",
      "escova", "espelho", "espada",
      "faca", "fita", "fogao",
      "garfo", "garrafa", "gaiola",
      "harpa", "helice", "hidrante",
      "ima", "isqueiro", "ioio",
      "janela", "jarra", "joia",
      "kit", "kart", "kimono",
      "lapis", "livro", "luminaria",
      "mesa", "mochila", "martelo",
      "navalha", "notebook", "novelo",
      "oculos", "otoscopio", "ourivesaria",
      "prato", "panela", "pente",
      "quadro", "quebra-cabeca", "quimono",
      "relogio", "radio", "regua",
      "sapato", "sofa", "sino",
      "tesoura", "telefone", "tapete",
      "urna", "umidificador", "uniforme",
      "vassoura", "vaso", "vela",
      "walkman", "web-cam", "wafer",
      "xicara", "xale", "xilofone",
      "yo-yo", "yardstick", "yoga",
      "ziper", "zabumba", "zarelho"
    ],
    comida: [
      "arroz", "abacaxi", "alface",
      "banana", "batata", "bife",
      "cebola", "cenoura", "carne",
      "doce", "damasco", "dobradinha",
      "espinafre", "empada", "ervilha",
      "feijao", "farofa", "frango",
      "goiaba", "gelatina", "grao-de-bico",
      "hamburguer", "hortela", "hot-dog",
      "iogurte", "inhame", "ica",
      "jaca", "jilo", "jabuticaba",
      "ketchup", "kiwi", "kibe",
      "laranja", "limao", "lasanha",
      "maca", "macarrao", "melancia",
      "nectarina", "nabo", "noz",
      "ovo", "omelete", "ostra",
      "pizza", "pastel", "pipoca",
      "queijo", "quindim", "quibe",
      "rabanete", "roma", "rucula",
      "sopa", "salada", "salsicha",
      "tomate", "trigo", "torrada",
      "uva", "umbu", "uva-passa",
      "vagem", "vinagre", "vitamina",
      "waffle", "wafer", "wasabi",
      "x-salada", "x-burguer", "xis",
      "yakisoba", "yoki", "yorgute",
      "zimbro", "zaatar", "zampone"
    ],
    cor: [
      "azul", "amarelo", "aquamarine",
      "branco", "bege", "bordo",
      "cinza", "castanho", "ciano",
      "dourado", "damasco", "denim",
      "esmeralda", "escarlate", "ebano",
      "fucsia", "ferrugem", "fogo",
      "gelo", "grafite", "grena",
      "heliotropio", "holografico", "herbal",
      "indigo", "marfim", "isabel",
      "jambo", "jade", "jaspe",
      "caqui", "kiwi", "ketchup",
      "laranja", "lilas", "lima",
      "marrom", "magenta", "mostarda",
      "negro", "naval", "nude",
      "ouro", "oliva", "orquidea",
      "preto", "prata", "purpura",
      "quartzo", "quaresma", "quente",
      "rosa", "roxo", "rubi",
      "salmao", "sepia", "salvia",
      "turquesa", "terracota", "tijolo",
      "uva", "urano", "ultramar",
      "verde", "vermelho", "violeta",
      "wine", "wheat", "wasabi",
      "xanadu", "xantico", "xale",
      "yellow", "yam", "yuan",
      "zarcao", "zimbro", "zafre"
    ],
    cep: [
      "argentina", "alemanha", "angola",
      "brasil", "bahia", "belem",
      "canada", "chile", "china",
      "dinamarca", "dublin", "detroit",
      "equador", "egito", "espanha",
      "franca", "finlandia", "fortaleza",
      "goias", "goiania", "grecia",
      "holanda", "honduras", "haiti",
      "italia", "india", "indonesia",
      "japao", "jamaica", "jordania",
      "kuwait", "quenia", "kiev",
      "lisboa", "lima", "londres",
      "mexico", "marrocos", "maranhao",
      "noruega", "natal", "niteroi",
      "osasco", "olinda", "orlando",
      "portugal", "peru", "parana",
      "catar", "quixada", "quito",
      "roraima", "recife", "rio de janeiro",
      "sao paulo", "sergipe", "salvador",
      "toquio", "toronto", "tailandia",
      "uruguai", "ucrania", "uganda",
      "venezuela", "vietna", "vitoria",
      "washington", "wales", "warsaw",
      "xangai", "xique-xique", "xanxere",
      "yokohama", "yamagata", "yaounde",
      "zambia", "zimbabue", "zurique"
    ],
    fruta: [
      "abacate", "acerola", "ameixa",
      "banana", "bacuri", "buriti",
      "caju", "caqui", "cereja",
      "damasco", "diospiro", "duriao",
      "esfregao", "embauba", "engaco",
      "figo", "framboesa", "fruta-pao",
      "goiaba", "graviola", "roma",
      "hevea", "hibrida", "hawthorn",
      "inaja", "imbu", "ilama",
      "jaca", "jabuticaba", "jambo",
      "kiwi", "kinkan", "karat",
      "limao", "laranja", "lichia",
      "melancia", "morango", "manga",
      "nectarina", "nespera", "noz",
      "oriri", "oiti", "olho-de-boi",
      "pera", "pessego", "pitanga",
      "quina", "quena", "quariquari",
      "rambuta", "rubia", "seriguela",
      "sapoti", "sapucaia", "tangerina",
      "tomate", "tamara", "uva",
      "umbu", "uvaia", "veludo",
      "vacinio", "vime", "wampi",
      "wolfberry", "white-currant", "ximbo",
      "xixa", "xique-xique", "yamamomo",
      "yuzu", "yangmei", "zimbro",
      "zizifo", "zambujo"
    ],
    planta: [
      "anturio", "azaleia", "avenca",
      "bromelia", "brinco-de-princesa", "begonia",
      "cravo", "crisantemo", "cacto",
      "dalia", "dente-de-leao", "dracena",
      "espada-de-sao-jorge", "estrelicia", "eucalipto",
      "ficus", "flor-de-lotus", "freesia",
      "girassol", "geranio", "hortensia",
      "hibisco", "hera", "iris",
      "ipe", "inhame-da-africa", "jasmim",
      "jacaranda", "jurema", "kalanchoe",
      "kentia", "kumquat", "lirio",
      "lotus", "lavanda", "margarida",
      "manaca", "mentrasto", "narciso",
      "nenufar", "nim", "orquidea",
      "onze-horas", "oliveira", "petunia",
      "palmeira", "pinheiro", "quaresmeira",
      "quina", "quebra-pedra", "rosa",
      "reseda", "ricino", "samambaia",
      "salvia", "suculenta", "tulipa",
      "trevo", "taja", "unha-de-gato",
      "uva-de-urso", "urucum", "violeta",
      "vinca", "verbena", "washingtonia",
      "wisteria", "wolffiella", "xaxim",
      "xanana", "xique-xique", "yucca",
      "ylang-ylang", "yam", "zinia",
      "zamioculca", "zimbro"
    ],
    inseto: [
      "aranha", "abelha", "antena",
      "borboleta", "besouro", "barata",
      "cigarra", "cupim", "centopeia",
      "dengue", "donzelinha", "drosofila",
      "escorpiao", "esperanca", "escavelho",
      "formiga", "flebotomo", "forficula",
      "gafanhoto", "gorgulho", "grilo",
      "heperideo", "hidrometra", "himenia",
      "inseto-pau", "iris", "isopode",
      "joaninha", "jequitiranaboia", "jundia",
      "kissing-bug", "kalotermes", "kricogonia",
      "louva-a-deus", "lagarta", "libelula",
      "mosca", "mosquito", "mariposa",
      "nematode", "neoptera", "neuroptera",
      "odonata", "orthoptera", "ouvidor",
      "percevejo", "pulga", "piolho",
      "quironomideo", "quenquem", "queima-queima",
      "ralo-da-horta", "reduvideo", "rino",
      "sauva", "sarna", "simulio",
      "traca", "taturana", "tenebrio",
      "urura", "urocerus", "utetheisa",
      "vespa", "vaga-lume", "vinchuca",
      "weta", "walking-stick", "weaver-ant",
      "xilocopa", "xyloryctidae", "xis-inseto",
      "yponomeuta", "ypsolopha", "yellow-jacket",
      "zangao", "zoraptero", "zygentoma"
    ],
    corpo: [
      "antebraco", "abdomen", "articulacao",
      "braco", "boca", "bochecha",
      "cabeca", "coracao", "cotovelo",
      "dedo", "dente", "diafragma",
      "estomago", "esofago", "ombro",
      "figado", "femur", "fronte",
      "garganta", "gengiva", "gluteo",
      "himen", "hipofise", "hipotalamo",
      "intestino", "iris", "isquio",
      "joelho", "jugular", "junta",
      "keratin", "kidneys", "knee",
      "lingua", "laringe", "lobo",
      "mao", "musculo", "menton",
      "nariz", "nuca", "nervo",
      "olho", "ouvido", "perna",
      "pe", "pulmao", "queixo",
      "quadril", "queratina", "rim",
      "rotula", "retina", "sangue",
      "sobrancelha", "seio", "tornozelo",
      "tibia", "triceps", "unha",
      "utero", "uretra", "veia",
      "ventriculo", "vesicula", "wernicke",
      "womb", "wrist", "xifoide",
      "xisto", "xilofonio", "youtube-muscular",
      "ypsiloide", "y-cromossomo", "zigomatico",
      "zoide", "zona"
    ],
    clima: [
      "aurora", "arco-iris", "avalanche",
      "brisa", "nevasca", "borrasca",
      "chuva", "ciclone", "calor",
      "degelo", "diluvio", "depressao",
      "estiagem", "eclipse", "enchente",
      "frio", "furacao", "nevoa",
      "geada", "granizo", "garoa",
      "humidade", "halo", "inundacao",
      "inverno", "incendio", "jato",
      "juventude", "juvia", "katabatic",
      "khamsin", "karst", "lampejo",
      "lua", "leste", "moncao",
      "mare", "nuvem", "orvalho",
      "onda", "oeste", "precipitacao",
      "penumbra", "poeira", "quentura",
      "queimada", "quebra-mar", "raio",
      "ressaca", "rajada", "sol",
      "seca", "sismo", "tornado",
      "tempestade", "trovao", "umidade",
      "uragano", "umbra", "vento",
      "verao", "vendaval", "willy-willy",
      "whiteout", "windchill", "xara",
      "xilocopa", "xis-vento", "yardang",
      "yua", "yellow-wind", "zenite",
      "zeferino", "zefiro"
    ],
    filme: [
      "avatar", "aladin", "alien",
      "batman", "barbie", "blade",
      "coringa", "carros", "cinderella",
      "deadpool", "divertidamente", "dune",
      "eternos", "enrolados", "elvis",
      "frozen", "furiosa", "ficcao",
      "gladiador", "godzilla", "genese",
      "hercules", "her", "hancock",
      "inception", "interstellar", "it",
      "jumanji", "jaws", "joker",
      "king-kong", "kill-bill", "klaus",
      "logan", "luzes", "linha",
      "matrix", "mulan", "minions",
      "nemo", "noah", "nope",
      "oblivion", "old", "onward",
      "pinoquio", "pearl", "psico",
      "quarto", "quantumania", "quiz",
      "rambo", "ratatouille", "ringo",
      "shrek", "superman", "saw",
      "titanic", "tarzan", "thor",
      "uncharted", "up", "us",
      "venom", "vertigo", "vovo",
      "wall-e", "whiplash", "wicked",
      "x-men", "xuxa", "x-files",
      "yesterday", "yes-man", "yojimbo",
      "zootopia", "zorro", "zumbilandia"
    ],
    desenho: [
      "avatar", "naruto", "astroboy",
      "ben-10", "bleach", "bakugan",
      "coragem", "caverna", "cyberpunk",
      "digimon", "dora", "dragon-ball",
      "evangelion", "ed-edd-n-eddy", "elfo",
      "futurama", "fairy-tail", "flintstones",
      "gintama", "gargoyles", "garfield",
      "he-man", "haikyuu", "hellsing",
      "inuyasha", "incredibles", "invincible",
      "jujutsu-kaisen", "jojo", "johnny-bravo",
      "kaisen", "kim-possible", "kirby",
      "looney-tunes", "luffy", "lucky",
      "miraculous", "monster", "madagascar",
      "one-piece", "overlord", "oggy",
      "pokemon", "peppa", "phineas",
      "quack-pack", "queen-millennia", "q-version",
      "rick-and-morty", "rugrats", "robin",
      "simpsons", "spongebob", "shrek",
      "tom-and-jerry", "tarzan", "titans",
      "ultraman", "uncle-grandpa", "ultimate",
      "voltron", "vinland-saga", "violet-evergarden",
      "winx", "wakfu", "wolverine",
      "x-men", "xiaolin", "x-men-evolution",
      "yu-gi-oh", "yu-yu-hakusho", "yo-kai",
      "zatch-bell", "zorro", "zombieland-saga"
    ],
    celebridade: [
      "anitta", "adele", "alckmin",
      "beyonce", "brad-pitt", "bieber",
      "cruise", "cher", "caetano",
      "drake", "dicaprio", "dua-lipa",
      "eminem", "eliana", "elba",
      "faustao", "ferrugem", "fabio-assuncao",
      "gaga", "gal-costa", "gagliasso",
      "harry-styles", "halsey", "hanks",
      "ivete-sangalo", "iza", "idris-elba",
      "j-balvin", "jojo-todynho", "justin",
      "kanye-west", "keanu-reeves", "katy-perry",
      "lula", "luan-santana", "ludmilla",
      "madonna", "neymar", "maroon-5",
      "nicolas-cage", "natalie-portman", "otaviano-costa",
      "ozzy", "orlando-bloom", "pitt",
      "pablo-vittar", "pele", "queen-latifah",
      "quico", "quavo", "rihanna",
      "ronaldinho", "ryan-gosling", "shakira",
      "silvio-santos", "sandy", "tom-cruise",
      "taylor-swift", "travis-scott", "usher",
      "uma-thurman", "u2", "vin-diesel",
      "valesca", "vitor-kley", "will-smith",
      "wendy", "wesley-safadao", "xuxa",
      "xama", "xororo", "yasmin-brunet",
      "yudi", "yoongi", "zendaya",
      "zeca-pagodinho", "zeze"
    ],
    personagem: [
      "ariel", "aladdin", "aragorn",
      "batman", "barbie", "buzz",
      "coringa", "cinderella", "cebolinha",
      "dumbo", "dracula", "deadpool",
      "elsa", "eric", "eleven",
      "fiona", "frodo", "flash",
      "goku", "gandalf", "garfield",
      "harry-potter", "hulk", "homer",
      "iron-man", "inuyasha", "indiana-jones",
      "joker", "jaspion", "jerry",
      "kakashi", "kirby", "katniss",
      "luigi", "luffy", "legolas",
      "mickey", "mario", "mulan",
      "naruto", "nemo", "neo",
      "olaf", "optimus", "obelix",
      "pikachu", "popeye", "peter-pan",
      "quico", "quasimodo", "quicksilver",
      "rambo", "robin", "ronaldinho",
      "shrek", "superman", "sonic",
      "thor", "tarzan", "ursinho-pooh",
      "usagi", "ursula", "voldemort",
      "vegeta", "velma", "wolverine",
      "woody", "wanda", "x-men",
      "xena", "xavier", "yoshi",
      "yoda", "yugi", "zorro",
      "zeus", "zeca-urubu"
    ],
    musica: [
      "aerosmith", "abba", "anitta",
      "beatles", "beyonce", "blink-182",
      "coldplay", "capital-inicial", "cpm-22",
      "drake", "dua-lipa", "daft-punk",
      "evanescence", "eminem", "eagles",
      "foo-fighters", "ferrugem", "fresno",
      "gorillaz", "green-day", "guns-n-roses",
      "helloween", "halsey", "him",
      "iron-maiden", "imagine-dragons", "ira",
      "jota-quest", "jao", "javali",
      "kiss", "korn", "katy-perry",
      "linkin-park", "legiao-urbana", "ludmilla",
      "metallica", "muse", "maroon-5",
      "nirvana", "nightwish", "nx-zero",
      "oasis", "offspring", "one-direction",
      "pink-floyd", "pearl-jam", "pitty",
      "queen", "queens-of-the-stone-age", "quavo",
      "rammstein", "rush", "rihanna",
      "slipknot", "skank", "system-of-a-down",
      "travis-scott", "twenty-one-pilots", "titas",
      "u2", "ultraje", "usher",
      "van-halen", "vampire-weekend", "vanguart",
      "weezer", "wham", "within-temptation",
      "xutos-e-pontapes", "xutos", "xama",
      "yes", "yo-la-tengo", "yanni",
      "zz-top", "zeppelin", "zeca-baleiro"
    ],
    profissao: [
      "advogado", "arquiteto", "ator",
      "biologo", "bombeiro", "biomedico",
      "contador", "chef", "cientista",
      "dentista", "designer", "delegado",
      "engenheiro", "enfermeiro", "economista",
      "fisioterapeuta", "fisico", "fotografo",
      "geologo", "gerente", "garcom",
      "historiador", "hoteleiro", "higienista",
      "ilustrador", "informatico", "instrumentista",
      "jornalista", "juiz", "jardineiro",
      "kartista", "kinesiologista", "ketchupista",
      "locutor", "livreiro", "lavrador",
      "medico", "motorista", "marceneiro",
      "nutricionista", "neurologista", "notario",
      "odontologista", "oceanografo", "operario",
      "professor", "policial", "psicologo",
      "quimico", "quiropraxista", "quituteiro",
      "radiologista", "recepcionista", "reporter",
      "sociologo", "serralheiro", "soldador",
      "veterinario", "tecnico", "tradutor",
      "urologista", "urbanista", "usineiro",
      "vigilante", "vidraceiro", "web-designer",
      "web-developer", "welder", "xilografo",
      "xaripeiro", "xariano", "youtube-creator",
      "yogi", "yo-yoer", "zootecnista",
      "zelador", "zoologo"
    ],
    esporte: [
      "atletismo", "automobilismo", "badminton",
      "basquete", "boxe", "boliche",
      "ciclismo", "canoagem", "capoeira",
      "dardos", "decatlo", "danca",
      "esgrima", "escalada", "esqui",
      "futebol", "futsal", "futevolei",
      "ginastica", "golfe", "goalball",
      "handebol", "hoquei", "hipismo",
      "iatismo", "ice-hockey", "inline-hockey",
      "judo", "jiu-jitsu", "joguete",
      "karate", "kart", "kickboxing",
      "luta-livre", "lacrosse", "luge",
      "motociclismo", "maratona", "mma",
      "natacao", "netball", "naval",
      "orientacao", "obstaculos", "octatlo",
      "polo", "patinacao", "padel",
      "quadribol", "quarterback", "quatlo",
      "rugby", "remo", "rali",
      "surfe", "skate", "squash",
      "tenis", "taekwondo", "triatlo",
      "ultimate-frisbee", "ultra-maratona", "uniciclismo",
      "volei", "vela", "volteio",
      "water-polo", "windsurf", "wakeboard",
      "xadrez", "x-games", "xadrez-boxe",
      "yoga", "yole", "yachting",
      "zumba", "zid", "zip-lining"
    ],
    roupa: [
      "anel", "alianca", "agasalho",
      "blusa", "bota", "bone",
      "camisa", "calca", "cinto",
      "doublet", "diadema", "doudoune",
      "estola", "echarpe", "espartilho",
      "fivela", "fato", "franja",
      "gravata", "gorro", "galocha",
      "halter", "handbag", "hoodie",
      "impermeavel", "ioio", "imenso",
      "jaqueta", "joia", "jardineira",
      "kilt", "quimono", "kway",
      "luva", "lenco", "legging",
      "meia", "mochila", "mocassim",
      "noiva", "necktie", "nightgown",
      "oculos", "ouro", "overalls",
      "pantufa", "paleto", "pulseira",
      "quepe", "quica", "relogio",
      "renda", "robe", "sapato",
      "saia", "sutia", "tenis",
      "terno", "touca", "uniforme",
      "unkle-boots", "underwear", "vestido",
      "veu", "viseira", "windbreaker",
      "watch", "waistcoat", "xale",
      "xororo", "xis-chinelo", "yarmulke",
      "yoga-pants", "yard", "ziper",
      "zabumba-alca", "zibelina"
    ],
    marca: [
      "apple", "adidas", "amazon",
      "burger-king", "bmw", "boticario",
      "coca-cola", "chevrolet", "calvin-klein",
      "dell", "disney", "dior",
      "ebay", "epson", "embraer",
      "ford", "fiat", "ferrari",
      "google", "gucci", "gillette",
      "honda", "hyundai", "hasbro",
      "intel", "ibm", "instagram",
      "jordan", "jeep", "jbs",
      "kelloggs", "kia", "kodak",
      "lg", "lego", "levis",
      "mcdonalds", "microsoft", "mercedes",
      "nike", "nestle", "netflix",
      "oracle", "oreo", "omo",
      "pepsi", "puma", "porsche",
      "quaker", "quiksilver", "qualcomm",
      "rolex", "red-bull", "renault",
      "samsung", "sony", "starbucks",
      "toyota", "tesla", "twitter",
      "uber", "unilever", "under-armour",
      "visa", "vivo", "volkswagen",
      "walmart", "warner", "whatsapp",
      "xiaomi", "xerox", "xbox",
      "youtube", "yahoo", "yamaha",
      "zara", "zaffari", "zoom"
    ],
    adjetivo: [
      "alto", "amavel", "agil",
      "bonito", "bravo", "baixo",
      "calmo", "chato", "corajoso",
      "doido", "doce", "dedicado",
      "esperto", "educado", "elegante",
      "forte", "feliz", "fiel",
      "grande", "gentil", "gordo",
      "honesto", "humilde", "habil",
      "inteligente", "injusto", "integro",
      "jovem", "justo", "jovial",
      "kafkaesco", "kawaii", "keen",
      "legal", "lindo", "lento",
      "magro", "mau", "maluco",
      "nobre", "nervoso", "novo",
      "otimista", "orgulhoso", "obeso",
      "pobre", "perto", "paciente",
      "querido", "quente", "quieto",
      "rico", "rapido", "ruim",
      "sabio", "sujo", "simpatico",
      "triste", "timido", "teimoso",
      "unico", "util", "urgente",
      "velho", "veloz", "verdadeiro",
      "wise", "wild", "weak",
      "xarope", "xenofobo", "xodo",
      "young", "yellow", "yielding",
      "zeloso", "zangado", "zero"
    ],
    cozinha: [
      "avental", "armario", "assadeira",
      "batedeira", "bacia", "balcao",
      "colher", "copo", "cafeteira",
      "detergente", "desidratador", "doceira",
      "escumadeira", "esponja", "exaustor",
      "fogao", "faca", "freezer",
      "garfo", "geladeira", "garrafa",
      "hot-dog-maker", "hortela", "haltere",
      "iogurteira", "isqueiro", "infusor",
      "jarra", "janela", "jogo-americano",
      "ketchup", "kit-de-facas", "kettle",
      "liquidificador", "lixeira", "leiteira",
      "mesa", "micro-ondas", "mixer",
      "nozes", "navalha", "ninho",
      "organista", "oleo", "omeleteira",
      "panela", "prato", "pano-de-prato",
      "queijeira", "quebrador-de-nozes", "querosene",
      "ralo", "rolo-de-massa", "radio",
      "sabao", "saca-rolhas", "sanduicheira",
      "torneira", "torradeira", "tigela",
      "utensilio", "umidificador", "urna",
      "vassoura", "vaso", "vinagre",
      "waffle-maker", "wok", "wafer",
      "xicara", "xarope", "xis-burger",
      "yakisoba-pan", "yoki", "yuzu",
      "zaatar", "zimbro", "ziper"
    ],
    escola: [
      "apontador", "agenda", "antena",
      "borracha", "bloco", "biombo",
      "caderno", "caneta", "clipes",
      "diario", "dicionario", "datador",
      "estojo", "esquadro", "envelope",
      "fita-adesiva", "fichario", "furador",
      "giz", "grampeador", "goma",
      "highlight", "horario-escolar", "holofote",
      "ima", "impressora", "isqueiro",
      "jaleco", "jornal", "jogo",
      "kit-de-desenho", "keyboard", "kraft-papel",
      "lapis", "livro", "lapiseira",
      "mochila", "marcador", "mural",
      "notebook", "novelo", "nivel",
      "organizador", "otoscopio", "oficio-papel",
      "papel", "pasta", "pincel",
      "quadro-negro", "quadro-branco", "querosene",
      "regua", "rascunho", "relatorio",
      "sulfite", "sacola", "selo",
      "tesoura", "tinta", "transferidor",
      "uniforme", "urna-votacao", "utensilio",
      "visualizador", "verniz", "vaso",
      "whiteboard", "word-pad", "webcam",
      "xerox", "xis-pasta", "xilofone",
      "yellow-pad", "yoga-mat", "youtube-kit",
      "ziper-pasta", "zarcao", "zero-grau"
    ],
    eletronico: [
      "ar-condicionado", "aspirador", "adega",
      "batedeira", "blender", "blu-ray",
      "celular", "computador", "chuveiro",
      "dvd", "desumidificador", "discman",
      "exaustor", "espremedor", "escova-eletrica",
      "fogao", "freezer", "forno",
      "geladeira", "grill", "gravador",
      "home-theater", "hub", "headset",
      "ipad", "iphone", "impressora",
      "juicer", "jogo-eletronico", "jukebox",
      "kindle", "keyboard", "kitchenaid",
      "liquidificador", "lampada", "lanterna",
      "micro-ondas", "monitor", "mouse",
      "notebook", "nintendo", "navio",
      "overloque", "otoscopio", "ouvidor",
      "pipoqueira", "processador", "projetor",
      "queijeira-eletrica", "aquecedor", "querosene-bomba",
      "radio", "roteador", "relogio",
      "smart-tv", "secador", "soundbar",
      "telefone", "tablet", "torradeira",
      "umidificador", "ultrabook", "usb-drive",
      "ventilador", "video-game", "vitrola",
      "walkman", "washer", "webcam",
      "xbox", "xiaomi", "xerox",
      "youtube-box", "yp-player", "yes-phone",
      "zoom-camera", "zenith-radio", "z-box"
    ],
    transporte: [
      "aviao", "automovel", "ambulancia",
      "bicicleta", "barco", "bonde",
      "carro", "caminhao", "carroca",
      "drone", "dique", "dirigivel",
      "escavadeira", "eletrico", "egua",
      "foguete", "furgao", "fragata",
      "gaiola", "guindaste", "gondola",
      "helicoptero", "hovercraft", "hidroaviao",
      "iate", "iola", "intertrens",
      "jato", "jeep", "jangada",
      "kart", "kombi", "kayak",
      "lancha", "locomotiva", "limusine",
      "moto", "metro", "monotrilho",
      "navio", "nautilo", "nau",
      "onibus", "onibus-espacial", "ourivesaria",
      "patinete", "picape", "patins",
      "quadriciclo", "quad", "querino-carro",
      "rali", "rodo-trem", "reboque",
      "submarino", "scooter", "skate",
      "trem", "trator", "taxi",
      "uber", "uniciclo", "utilitario",
      "van", "veleiro", "vagao",
      "wagon", "windsurf", "water-taxi",
      "xarda-barco", "xebeco", "xis-carro",
      "yacht", "yole", "yellow-cab",
      "zeppelin", "zodiaco", "zica"
    ],
    lugar: [
      "acougue", "aeroporto", "asilo",
      "banco", "bar", "biblioteca",
      "cinema", "correio", "creche",
      "delegacia", "drogaria", "deposito",
      "escola", "estacao", "estadio",
      "farmacia", "feira", "floricultura",
      "garagem", "ginasio", "galeria",
      "hospital", "hotel", "horto",
      "igreja", "industria", "instituto",
      "jardim", "joalheria", "juizado",
      "kiosk", "kartodromo", "kennel",
      "livraria", "loterica", "lavanderia",
      "mercado", "museu", "monumento",
      "necroterio", "niteroi", "notariado",
      "oficinas", "orfanato", "ouvidoria",
      "parque", "padaria", "praca",
      "quartel", "quitanda", "quiosque",
      "restaurante", "rodoviaria", "represa",
      "supermercado", "shopping", "sorveteria",
      "teatro", "terminal", "templo",
      "universidade", "upa", "usina",
      "vidracaria", "veterinaria", "viveiro",
      "walmart", "water-park", "workplace",
      "xadrez", "xangai", "xis-lanchonete",
      "yoga-studio", "youth-hostel", "yacht-club",
      "zoologico", "zona", "zaffari"
    ],
    sentimento: [
      "amor", "alegria", "angustia",
      "bondade", "brava", "bravo",
      "ciume", "carinho", "coragem",
      "desespero", "desejo", "desprezo",
      "empatia", "entusiasmo", "esperanca",
      "felicidade", "frustracao", "furia",
      "gratidao", "ganancia", "gosto",
      "humildade", "horror", "hostilidade",
      "inveja", "ira", "inseguranca",
      "jubilo", "justica", "juventude",
      "kawaii", "keenness", "kairos",
      "luto", "luxuria", "lealdade",
      "medo", "melancolia", "magoa",
      "nostalgia", "nojo", "nervosismo",
      "orgulho", "odio", "otimismo",
      "paixao", "pena", "prazer",
      "querenca", "quietude", "querencia",
      "raiva", "remorso", "respeito",
      "saudade", "solitude", "simpatia",
      "tristeza", "tedio", "terror",
      "uniao", "urgencia", "unidade",
      "vaidade", "vinganca", "vergonha",
      "wonder", "warmth", "worry",
      "xodo", "xenofobia", "xara",
      "yearning", "yielding", "yin-yang",
      "zelo", "zanga", "zoada"
    ],
    verbo: [
      "amar", "andar", "abrir",
      "beber", "brincar", "correr",
      "cantar", "comer", "chorar",
      "dancar", "dizer", "dormir",
      "estudar", "escrever", "encontrar",
      "falar", "fazer", "fugir",
      "ganhar", "gostar", "gritar",
      "haver", "habitar", "honrar",
      "ir", "imaginar", "imprimir",
      "jogar", "jantar", "juntar",
      "kikar", "knockar", "kidnappar",
      "ler", "lavar", "levar",
      "morrer", "morar", "mudar",
      "nadar", "nascer", "negar",
      "olhar", "ouvir", "organizar",
      "pensar", "pedir", "pular",
      "querer", "quebrar", "queimar",
      "rir", "ralar", "responder",
      "sair", "sorrir", "sentar",
      "ter", "trazer", "trabalhar",
      "usar", "unir", "urgir",
      "ver", "vir", "vender",
      "walk", "work", "write",
      "xingar", "xerocar", "xeretar",
      "yield", "yawn", "yelp",
      "zelar", "zangar", "zuar"
    ],
    coisa_verde: [
      "alface", "abacate", "arame",
      "brocolis", "bambu", "besouro",
      "capim", "clorofila", "couve",
      "dinheiro", "dolar", "dragao",
      "espinafre", "esmeralda", "ervilha",
      "folha", "formiga", "figueira",
      "grama", "grilo", "goiaba",
      "hortela", "hulk", "herbal",
      "iguana", "ipe-verde", "inhame",
      "jilo", "jade", "jacare",
      "kiwi", "kryptonita", "kero-kero",
      "limao", "lagarta", "lodo",
      "musgo", "melao", "maca",
      "nabo", "nectar", "nilo",
      "oliva", "olho", "orquidea",
      "pepino", "pimentao", "palmeira",
      "quiabo", "quina", "queijeira",
      "ra", "rucula", "repolho",
      "sapo", "salsa", "salada",
      "tomate", "trevo", "taturana",
      "uva", "umbu", "uranio",
      "vagem", "vento", "videira",
      "wasabi", "watermelon", "weed",
      "xale", "xexeu", "xisto",
      "yard", "yuzu", "yoda",
      "zucchini", "zimbro", "zebra"
    ],
    coisa_redonda: [
      "anel", "alianca", "alvo",
      "bola", "botao", "biscoito",
      "copo", "coroa", "colar",
      "dado", "disco", "doce",
      "esfera", "espelho", "elastico",
      "flor", "fruta", "fivela",
      "globo", "gotas", "guirlanda",
      "helice", "halo", "hamburguer",
      "ioio", "ima", "injecao",
      "janela", "jarra", "joia",
      "kiwi", "ketchup", "kart",
      "lua", "laranja", "lente",
      "moeda", "melancia", "mesa",
      "nozes", "navio", "ninho",
      "olho", "ovo", "oculos",
      "prato", "pneu", "planeta",
      "queijo", "quadro", "quindim",
      "roda", "relogio", "rosca",
      "sol", "sino", "saco",
      "tomate", "tampa", "tigela",
      "uva", "urna", "urano",
      "vaso", "volante", "vela",
      "wafer", "walkman", "wok",
      "xicara", "xale", "xis",
      "yo-yo", "yin-yang", "yuan",
      "ziper", "zero", "zabumba"
    ],
    instrumento: [
      "atabaque", "alaude", "acordeao",
      "baixo", "bateria", "berimbau",
      "cavaco", "clarinete", "chocalho",
      "djembe", "didgeridoo", "dulcimer",
      "escaleta", "espineta", "efe",
      "flauta", "fagote", "fiddle",
      "guitarra", "ganza", "gongo",
      "harpa", "harmonica", "horn",
      "instrumento", "idiofone", "invencao",
      "jongo", "jurema", "jube",
      "kazoo", "keytar", "koto",
      "lira", "maraca", "microfone",
      "melodica", "naval", "nabla",
      "nagara", "orgao", "ocarina",
      "oboe", "piano", "pandeiro",
      "prato", "quena", "queixada",
      "quintola", "reco-reco", "repique",
      "rabeca", "saxofone", "sitar",
      "surdo", "teclado", "triangulo",
      "tambor", "ukulele", "udu",
      "utensilio", "violao", "violino",
      "violoncelo", "washboard", "wagner-tuba",
      "whistle", "xilofone", "xequere",
      "xiao", "yueqin", "yatga",
      "yangqin", "zabumba", "zunidor",
      "zither"
    ],
    mitologia: [
      "anubis", "afrodite", "anjo",
      "buda", "baco", "brahma",
      "cupido", "centauro", "ciclope",
      "dionisio", "demeter", "diabo",
      "exu", "eros", "elfo",
      "fenix", "freya", "fada",
      "gabriel", "ganesha", "gaia",
      "hercules", "hades", "hermes",
      "icaro", "isis", "iemanja",
      "jesus", "jupiter", "jano",
      "krishna", "kali", "kronos",
      "lucifer", "loki", "lilith",
      "medusa", "minotauro", "moises",
      "netuno", "noe", "ninfas",
      "odin", "ogum", "osiris",
      "poseidon", "pandora", "pegaso",
      "quetzalcoatl", "quiron", "quirino",
      "ra", "reia", "rafael",
      "shiva", "sansao", "sereia",
      "thor", "ta", "tita",
      "urano", "ursula", "uriel",
      "venus", "vishnu", "valkiria",
      "wotan", "wicca", "wadjwer",
      "xango", "xama", "xiuhtecuhtli",
      "yemanja", "yahweh", "yuki-onna",
      "zeus", "zefiro", "zoroastro"
    ],
    influencer: [
      "alanzoka", "arthur aguiar", "andrezitos",
      "bianca andrade", "bruna vieira", "boca rosa",
      "casimiro", "cellbit", "carlinhos maia",
      "deolane", "davi brito", "diogo defante",
      "enaldinho", "ed gAMA", "evelyn regly",
      "felipe neto", "flavia pavanelli", "fernanda concon",
      "gkay", "gato galactico", "gusta stockler",
      "hariany almeida", "heloisa perisse", "hudson amorim",
      "ian neves", "isaac amendoim", "isaias",
      "jade picon", "juliette", "jout jout",
      "karen bachini", "kondzilla", "kefera",
      "luccas neto", "luba", "loud coringa",
      "maisa", "muca murioca", "manu gavassi",
      "nathalia arcuri", "nobru", "natan por aii",
      "orochinho", "olivia calabio", "ozzy",
      "pc siqueira", "pewdiepie", "paulo muzy",
      "quebrada queer", "queridometro", "quavo",
      "rezendeevil", "rafa kalimann", "rato borrachudo",
      "samira close", "t3ddy", "tata werneck",
      "tiringa", "tulio rocha", "uebershow",
      "virginia fonseca", "vitoria moraes", "viih tube",
      "whindersson nunes", "wendel bezerra", "windoh",
      "xurrasco", "xandao", "xuxa",
      "yudi tamashiro", "yasmin brunet", "yoongi",
      "zezinho", "zangado", "zeca camargo"
    ],
    jlr: [
      "among us", "a culpa e das estrelas", "aventuras na historia",
      "banco imobiliario", "battlefield", "bravo",
      "capitaes da areia", "coringa", "caros amigos",
      "detetive", "dom casmurro", "diario de um banana",
      "elden ring", "estadao", "epoca",
      "fortnite", "fahrenheit 451", "forbes",
      "god of war", "gibi", "galileu",
      "harry potter", "halo", "herois da marvel",
      "it", "inferno", "isto e",
      "jumanji", "jogo da vida", "jornal nacional",
      "kirby", "kingdom hearts", "kafka a metamorfose",
      "league of legends", "livro dos recordes", "lord of the rings",
      "minecraft", "monica", "mundo estranho",
      "naruto", "need for speed", "nova escola",
      "one piece", "o cortico", "o hobbit",
      "pokemon", "playstation", "piaui",
      "queda de gigantes", "quatro rodas", "quem",
      "resident evil", "roblox", "recreio",
      "super mario", "senhor dos aneis", "superinteressante",
      "the sims", "tetris", "turma da monica",
      "uno", "uncharted", "universo marvel",
      "valorant", "veja", "vogue",
      "war", "warcraft", "wired",
      "x-men", "xbox", "xadrez",
      "yu-gi-oh", "yoshi", "yakuza",
      "zelda", "zathura", "zero hora"
    ],
    remedio: [
      "aspirina", "azitromicina", "anador",
      "buscopan", "benegrip", "betametasona",
      "cetoprofeno", "cefalexina", "clonazepam",
      "dipirona", "dorflex", "dexametasona",
      "enalapril", "escitalopram", "expec",
      "fluoxetina", "furosemida", "flanax",
      "gardenal", "gliclazida", "glifage",
      "hidroclorotiazida", "histamin", "hidroxizina",
      "ibuprofeno", "ivermectina", "insulina",
      "janumet", "jardiance", "juliet",
      "ketoconazol", "kollagenase", "keflex",
      "losartana", "loratadina", "lactulona",
      "metformina", "meclin", "minoxidil",
      "nimesulida", "nebacetin", "novalgina",
      "omeprazol", "ozempic", "ondansetrona",
      "paracetamol", "prednisona", "pantoprazol",
      "quetiapina", "questran", "quinino",
      "rivotril", "rosuvastatina", "ranitidina",
      "sinvastatina", "soro fisiologico", "salbutamol",
      "torsilax", "tadalafila", "tandrilax",
      "ultraproct", "unizinco", "ursacol",
      "vick", "voltaren", "venlafaxina",
      "warfarina", "wellbutrin", "wintomylon",
      "xarelto", "xylocaina", "xantinon",
      "yasmin", "yaz", "yomax",
      "zinco", "zinnat", "zyrtec"
    ],
    espanhol: [
      "agua", "amigo", "amor",
      "bueno", "beso", "barrio",
      "casa", "coche", "comida",
      "dinero", "dia", "dolor",
      "escuela", "estrella", "espanol",
      "familia", "fiesta", "fuego",
      "gato", "gracias", "grande",
      "hola", "hombre", "hermano",
      "iglesia", "invierno", "izquierda",
      "jardin", "juego", "joven",
      "kilo", "karate", "koala",
      "libro", "luna", "lluvia",
      "madre", "mesa", "mundo",
      "nino", "noche", "nuevo",
      "ojo", "oro", "oso",
      "padre", "perro", "puerta",
      "queso", "quien", "querer",
      "rojo", "ropa", "rio",
      "sol", "silla", "sueno",
      "tarde", "tierra", "trabajo",
      "uno", "uva", "ultimo",
      "verde", "vida", "vino",
      "wifi", "whisky", "western",
      "xilofono", "xenofobia", "xenon",
      "yo", "yate", "yerba",
      "zapato", "zanahoria", "zorro"
    ],
    sabor_pizza: [
      "alho", "atum", "americana",
      "baiana", "bacon", "brocolis",
      "calabresa", "carne seca", "catupiry",
      "dois queijos", "doritos", "doce de leite",
      "escarola", "espinafre", "especial",
      "frango", "frango com catupiry", "file",
      "gorgonzola", "goiabada", "gratinada",
      "havaiana", "hortela", "hot dog",
      "italiana", "inglesa", "integral",
      "jardineira", "jerimum", "jalapeno",
      "kebab", "ketchup", "kiwi",
      "lombo", "linguica", "light",
      "marguerita", "mussarela", "milho",
      "napolitana", "nordestina", "nutella",
      "ovos", "oregano", "oliva",
      "portuguesa", "palmito", "pepperoni",
      "quatro queijos", "queijo", "quente",
      "rucula", "romana", "requeijao",
      "siciliana", "strogonoff", "salame",
      "tomate seco", "toscana", "tres queijos",
      "uva passa", "uruguaia", "umami",
      "vegetariana", "vienense", "verona",
      "wasabi", "wellington", "wafer",
      "x-bacon", "x-calabresa", "x-tudo",
      "yakisoba", "york", "yogurte",
      "zucchini", "zimbro", "zattar"
    ],
    presente: [
      "anel", "agenda", "almofada",
      "boneca", "bola", "bicicleta",
      "camiseta", "chocolate", "caneca",
      "drone", "diario", "disco",
      "estojo", "ebook", "escova",
      "fone", "flor", "frigideira",
      "game", "guitarra", "garrafa",
      "headset", "hoverboard", "hidratante",
      "iphone", "ingresso", "isqueiro",
      "joia", "jogo", "jaqueta",
      "kit", "kimono", "keyboard",
      "livro", "luminaria", "lego",
      "mochila", "maquiagem", "mouse",
      "notebook", "necessaire", "nintendo",
      "oculos", "organizador", "ouro",
      "perfume", "pulseira", "pelucia",
      "quadro", "quebra-cabeca", "quimono",
      "relogio", "roupa", "radio",
      "sapato", "smartwatch", "skate",
      "tablet", "tenis", "teclado",
      "ukulele", "urso", "uniforme",
      "violao", "voucher", "vinho",
      "webcam", "watch", "walkman",
      "xale", "xicara", "xbox",
      "yoyo", "yoga mat", "yacht",
      "ziper", "zabumba", "zapatilha"
    ],
    nome_masculino: [
      "arthur", "andre", "antonio",
      "bruno", "bernardo", "breno",
      "carlos", "caio", "caua",
      "daniel", "diego", "davi",
      "eduardo", "enrico", "eric",
      "felipe", "fernando", "fabio",
      "gustavo", "guilherme", "gabriel",
      "heitor", "henrique", "hugo",
      "igor", "icaro", "isaac",
      "joao", "jorge", "julio",
      "kaio", "kevin", "kleber",
      "lucas", "leonardo", "luiz",
      "matheus", "marcos", "miguel",
      "nicolas", "nathan", "nelson",
      "otavio", "orlando", "oscar",
      "pedro", "paulo", "patrick",
      "querino", "quincas", "queiroz",
      "rafael", "rodrigo", "renan",
      "samuel", "savio", "sergio",
      "thiago", "tomas", "theo",
      "ulisses", "uriel", "ubirajara",
      "victor", "vinicius", "vagner",
      "william", "wagner", "wesley",
      "xavier", "xisto", "xande",
      "yuri", "yago", "yan",
      "zacarias", "zeca", "ze"
    ],
    super_heroi: [
      "aquaman", "arqueiro verde", "ajax",
      "batman", "besouro azul", "blade",
      "capitao america", "coringa", "ciborgue",
      "demolidor", "doutor estranho", "deadpool",
      "elektra", "estrela negra", "elastigirl",
      "flash", "feiticeira escarlate", "falcao",
      "goku", "gambit", "gaviao arqueiro",
      "hulk", "homem aranha", "homem de ferro",
      "incrivel hulk", "invencivel", "iron fist",
      "justiceiro", "jean grey", "jaspion",
      "katana", "kid flash", "krypto",
      "lanterna verde", "loki", "logan",
      "mulher maravilha", "mulher elastica", "motoqueiro fantasma",
      "noturno", "nova", "namor",
      "oracle", "orion", "omega red",
      "pantera negra", "professor x", "punho de ferro",
      "quicksilver", "questao", "quake",
      "robin", "ravena", "rocket",
      "superman", "shazam", "surfista prateado",
      "thor", "tempestade", "tocha humana",
      "ultron", "ultra boy", "usagi",
      "venom", "vespa", "visao",
      "wolverine", "wanda", "wally west",
      "x-men", "xavier", "x-23",
      "yoda", "yellowjacket", "yondu",
      "zatanna", "zorro", "zeus"
    ],
    comida_saudavel: [
      "abacate", "arroz integral", "aveia",
      "banana", "batata doce", "brocolis",
      "cenoura", "chia", "couve",
      "damasco", "dourado", "detox",
      "espinafre", "ervilha", "edamame",
      "frango grelhado", "feijao", "fruta",
      "grao-de-bico", "granola", "goiaba",
      "hortela", "homus", "hamburguer vegano",
      "inhame", "iogurte natural", "integral",
      "jaca", "jilo", "jabuticaba",
      "kiwi", "kefir", "kombucha",
      "lentilha", "limao", "linhaca",
      "maca", "manga", "melancia",
      "nozes", "nectarina", "nabo",
      "omelete", "ovo cozido", "oregano",
      "peixe", "pera", "pepino",
      "quinoa", "quiabo", "queijo branco",
      "rucula", "ricota", "rabanete",
      "salada", "sopa", "salmao",
      "tomate", "tapioca", "tofu",
      "uva", "umbu", "uva passa",
      "vagem", "vitamina", "verduras",
      "whey", "wrap integral", "wasabi",
      "xarope natural", "xuxu", "xixa",
      "yakisoba integral", "yogurte", "yuzu",
      "zucchini", "zimbro", "zattar"
    ],
    app_site: [
      "amazon", "airbnb", "aliexpress",
      "booking", "bing", "bluesky",
      "canva", "chatgpt", "chrome",
      "discord", "duolingo", "deezer",
      "ebay", "evernote", "edge",
      "facebook", "figma", "firefox",
      "google", "gmail", "github",
      "hotmart", "habbo", "hbo max",
      "instagram", "ifood", "imdb",
      "jira", "jitsi", "jogos 360",
      "kwai", "kabum", "khan academy",
      "linkedin", "lojas americanas", "letterboxd",
      "mercado livre", "magalu", "medium",
      "netflix", "notion", "nubank",
      "olx", "outlook", "omegle",
      "pinterest", "paypal", "prime video",
      "quora", "quizlet", "quickbooks",
      "reddit", "roblox", "rappi",
      "spotify", "steam", "snapchat",
      "tiktok", "telegram", "twitch",
      "uber", "udemy", "ubereats",
      "vimeo", "vinted", "vivo",
      "whatsapp", "wikipedia", "waze",
      "x", "xbox", "xvideos",
      "youtube", "yahoo", "yelp",
      "zoom", "zillow", "zap imoveis"
    ],
    time_esportivo: [
      "atletico mineiro", "arsenal", "avai",
      "barcelona", "botafogo", "bahia",
      "corinthians", "cruzeiro", "chelsea",
      "dortmund", "dinamo zagreb", "dallas cowboys",
      "everton", "estudiantes", "eintracht frankfurt",
      "flamengo", "fluminense", "fortaleza",
      "gremio", "goias", "galatasaray",
      "hamburgo", "hull city", "hertha berlin",
      "internacional", "inter de milao", "ipswich",
      "juventus", "joinville", "juventude",
      "kaiser chiefs", "kashima antlers", "kyoto sanga",
      "liverpool", "lazio", "leicester",
      "manchester city", "milan", "monaco",
      "nautico", "napoli", "newcastle",
      "olympique", "osasuna", "orlando city",
      "palmeiras", "psg", "porto",
      "queens park", "queretaro", "qpr",
      "real madrid", "roma", "river plate",
      "santos", "sao paulo", "sport",
      "tottenham", "torino", "tigres",
      "udinese", "universidad chile", "union berlin",
      "vasco", "vitoria", "valencia",
      "west ham", "wolfsburg", "wolverhampton",
      "xamax", "xerez", "xv de piracicaba",
      "yokohama marinos", "young boys", "york city",
      "zenit", "zamalek", "zaragoza"
    ],
    idioma: [
      "arabe", "alemao", "armenio",
      "bulgaro", "bengali", "basco",
      "chines", "croata", "catalao",
      "dinamarques", "dari", "dutch",
      "espanhol", "esperanto", "estoniano",
      "frances", "finlandes", "filipino",
      "grego", "guarani", "georgiano",
      "hebraico", "hindi", "hungaro",
      "ingles", "italiano", "indonesio",
      "japones", "javanes", "judaico",
      "koreano", "kurdish", "kannada",
      "latim", "lituano", "letao",
      "mandarim", "malaio", "mongol",
      "noruegues", "nepales", "navajo",
      "olandes", "oriya", "osseta",
      "portugues", "polones", "persa",
      "quichua", "quirguiz", "quimbundo",
      "russo", "romeno", "romanche",
      "sueco", "servio", "sanscrito",
      "turco", "tcheco", "tailandes",
      "ucraniano", "urdu", "uzbeque",
      "vietnamita", "valenciano", "venda",
      "welsh", "wolof", "wallon",
      "xhosa", "xiang", "xavante",
      "yoruba", "yiddish", "yucateco",
      "zulu", "zapoteco", "zaza"
    ],
    serie: [
      "anne with an e", "arrow", "arcane",
      "breaking bad", "bridgerton", "black mirror",
      "chaves", "chernobyl", "cobra kai",
      "dark", "dexter", "doctor who",
      "elite", "euphoria", "er",
      "friends", "flash", "fargo",
      "game of thrones", "glee", "gotham",
      "hannibal", "house", "homeland",
      "icarly", "insecure", "invencivel",
      "jane the virgin", "joey", "justice",
      "killing eve", "kobra kai", "krypton",
      "lost", "lucifer", "lupin",
      "manifest", "modern family", "mr robot",
      "narcos", "ncis", "new girl",
      "ozark", "outer banks", "orphan black",
      "prison break", "peaky blinders", "pretty little liars",
      "quantico", "queer eye", "queen charlotte",
      "riverdale", "rebelde", "round 6",
      "stranger things", "suits", "supernatural",
      "the boys", "the office", "ted lasso",
      "umbrella academy", "unbreakable kimmy schmidt", "upload",
      "vikings", "vis a vis", "velma",
      "wandinha", "westworld", "white lotus",
      "xena", "x-files", "x-men",
      "yellowstone", "you", "young sheldon",
      "zoey 101", "z nation", "zorro"
    ],
    brinquedo: [
      "aviaozinho", "amarelinha", "arminha de agua",
      "boneca", "bola", "beyblade",
      "carrinho", "casinha", "cubo magico",
      "domino", "dado", "dinossauro",
      "encaixe", "escorregador", "espada",
      "ferrorama", "fantoche", "flauta de brinquedo",
      "gangorra", "gira-gira", "gude",
      "helicoptero", "hot wheels", "hula hoop",
      "ioio", "inflavel", "instrumento infantil",
      "jogo da memoria", "jenga", "jogo de tabuleiro",
      "kart de brinquedo", "kit medico", "kit cozinha",
      "lego", "lousa magica", "lanterna",
      "massinha", "miniatura", "mola maluca",
      "navio", "nerf", "nintendo",
      "oculos de brinquedo", "origami", "onibus de brinquedo",
      "patinete", "pipa", "peao",
      "quebra-cabeca", "quadriciclo", "quadro magico",
      "robo", "raquete", "radio controle",
      "skate", "slime", "soldadinho",
      "trenzinho", "tablet infantil", "tamagotchi",
      "ursinho", "uno", "unicorno",
      "violao infantil", "videogame", "varinha",
      "walkie-talkie", "water gun", "wii",
      "xilofone", "xale de fantasia", "xadrez",
      "yoyo", "yoshi", "yacht toy",
      "zebra de pelucia", "zabumba infantil", "zorro boneco"
    ]
  };

  const ALIASES = {
    nome: [
      "nome", "nomes", "pessoa",
      "pessoas", "nome proprio", "nome feminino",
      "nome feminino completo"
    ],
    animal: [
      "animal", "animais", "bicho",
      "bichos"
    ],
    objeto: [
      "objeto", "objetos", "coisa",
      "coisas"
    ],
    comida: [
      "alimento", "alimentos", "comida",
      "comidas", "prato", "culinaria"
    ],
    cor: [
      "cor", "cores"
    ],
    cep: [
      "cep", "cidade estado ou pais", "cidade estado pais",
      "cidade estado e pais", "cidade pais", "estado pais",
      "pais", "paises"
    ],
    fruta: [
      "fruta", "frutas"
    ],
    planta: [
      "flor", "flores", "planta",
      "plantas", "flor ou planta"
    ],
    inseto: [
      "inseto", "insetos", "artropode",
      "artropodes", "inseto ou artropode"
    ],
    corpo: [
      "parte do corpo", "corpo humano", "corpo",
      "parte do corpo humano"
    ],
    clima: [
      "clima", "tempo", "fenomeno natural",
      "fenomenos naturais", "clima tempo ou fenomeno natural"
    ],
    filme: [
      "filme", "filmes"
    ],
    desenho: [
      "desenho", "desenhos", "anime",
      "animes", "desenho animado", "desenho animado ou anime"
    ],
    celebridade: [
      "celebridade", "celebridades", "ator",
      "atores", "atriz", "cantor",
      "cantora", "famoso", "famosos"
    ],
    personagem: [
      "personagem", "personagens", "personagem ficticio",
      "personagens ficticios"
    ],
    musica: [
      "musica", "musicas", "banda",
      "bandas", "artista", "artistas",
      "cantor", "cancao"
    ],
    profissao: [
      "profissao", "profissoes", "trabalho",
      "cargo"
    ],
    esporte: [
      "esporte", "esportes", "modalidade"
    ],
    roupa: [
      "roupa", "roupas", "acessorio",
      "acessorios", "roupa ou acessorio", "vestuario",
      "vestimenta", "vestimentas"
    ],
    marca: [
      "marca", "marcas", "empresa",
      "empresas", "marca ou empresa"
    ],
    adjetivo: [
      "adjetivo", "adjetivos", "caracteristica",
      "caracteristicas", "qualidade"
    ],
    cozinha: [
      "cozinha", "coisa que tem na cozinha", "tem na cozinha",
      "objeto de cozinha"
    ],
    escola: [
      "objeto de escola", "escola", "escritorio",
      "objeto de escritorio", "objeto de escola ou escritorio", "material escolar"
    ],
    eletronico: [
      "eletrodomestico", "eletrodomesticos", "eletronico",
      "eletronicos", "eletrodomestico ou eletronico", "eletro eletronico",
      "eletro eletronicos", "eletro-eletronico"
    ],
    transporte: [
      "meio de transporte", "transporte", "transportes",
      "veiculo", "veiculos"
    ],
    lugar: [
      "lugares do bairro", "lugar do bairro", "bairro",
      "cidade", "lugares da cidade", "lugar da cidade"
    ],
    sentimento: [
      "sentimento", "sentimentos", "emocao",
      "emocoes", "sentimento ou emocao"
    ],
    verbo: [
      "verbo", "verbos", "acao",
      "acoes"
    ],
    coisa_verde: [
      "coisa verde", "coisas verdes", "verde"
    ],
    coisa_redonda: [
      "coisa redonda", "coisas redondas", "redondo",
      "redonda"
    ],
    instrumento: [
      "instrumento musical", "instrumentos musicais", "instrumento",
      "instrumentos"
    ],
    mitologia: [
      "mitologia", "religiao", "personagem da mitologia",
      "personagens da mitologia", "personagens da mitologia ou religiao"
    ],
    influencer: [
      "influencer", "influenciador", "influenciadora",
      "influenciadores", "criador de conteudo", "youtuber"
    ],
    jlr: [
      "jlr", "jogo livro revista", "jogo livro ou revista",
      "jogos livros revistas", "jogos livros e revistas"
    ],
    remedio: [
      "remedio", "remedios", "medicamento",
      "medicamentos", "farmacia"
    ],
    espanhol: [
      "palavra em espanhol", "espanhol", "palavras em espanhol",
      "palavra espanhola", "idioma espanhol"
    ],
    sabor_pizza: [
      "sabor de pizza", "sabor pizza", "pizza",
      "sabores de pizza"
    ],
    presente: [
      "presente", "presentes", "coisa para dar de presente",
      "coisas para dar de presente"
    ],
    nome_masculino: [
      "nome masculino", "nomes masculinos", "homem",
      "nome de homem", "pessoa masculina"
    ],
    super_heroi: [
      "super heroi", "super-heroi", "super herois",
      "super-herois", "heroi", "herois"
    ],
    comida_saudavel: [
      "comida saudavel", "comidas saudaveis", "alimento saudavel",
      "alimentos saudaveis", "saudavel"
    ],
    app_site: [
      "app ou site", "app", "site",
      "aplicativo", "aplicativos", "website"
    ],
    time_esportivo: [
      "time esportivo", "times esportivos", "time",
      "times", "clube", "clube esportivo"
    ],
    idioma: [
      "idioma", "idiomas", "lingua",
      "linguas", "linguagem"
    ],
    serie: [
      "serie", "series", "seriado",
      "seriados", "programa de tv"
    ],
    brinquedo: [
      "brinquedo", "brinquedos", "brincadeira",
      "brincadeiras"
    ]
  };

  window.StopotsHelperData = { DATA, ALIASES };
})();
